In [4]:
!pip install tensorflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 589.8/589.8 MB 2.3 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 10.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.5/24.5 MB 53.7 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.7/133.7 kB 21.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 77.9 MB/s eta 0:00:00:00:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 76.6 MB/s eta 0:00:00ta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.3/80.3 kB 16.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 75.3 MB/s eta 0:00:00:00:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 12.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 66.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 78.9 MB/s eta 0:00:00ta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 

# Answer1
TensorFlow, being a powerful framework for machine learning and deep learning, employs various data structures to handle data efficiently. Some of the key data structures used in TensorFlow include:

1. **Tensors**: Tensors are the fundamental data structure in TensorFlow, representing multi-dimensional arrays. These can be scalars, vectors, matrices, or higher-dimensional arrays. TensorFlow tensors are similar to NumPy arrays.

In [7]:
import tensorflow as tf

# Creating a tensor
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
print(tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


2. **Variables**: Variables are mutable tensors that hold values that can be updated during training. They are typically used to hold model parameters such as weights and biases.Example:

In [10]:
# Creating a variable
var = tf.Variable(5.0)
print(var.numpy())

5.0


3. **Datasets**: TensorFlow provides the tf.data.Dataset API for building efficient input pipelines. Datasets allow you to work with large amounts of data, perform transformations, and iterate over the data during training.Example:

In [15]:
# Creating a dataset from a list
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5])
print(dataset)
                                             

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>


4. **Sparse Tensors:** Sparse tensors are used to efficiently represent tensors with a large number of zero values. They are commonly used in applications such as natural language processing (NLP) and computer vision.Example:

In [26]:
# Creating a sparse tensor with indices of dtype int64
indices = tf.constant([[0, 0], [1, 2]])
indices = tf.cast(indices, tf.int64)  # Casting indices to int64
values = tf.constant([1, 2], dtype=tf.int32)
dense_shape = tf.constant([3, 4])
dense_shape = tf.cast(dense_shape,tf.int64)
sparse_tensor = tf.sparse.SparseTensor(indices, values, dense_shape)
print(sparse_tensor)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


5. **Ragged Tensors:** Ragged tensors are used to represent tensors with non-uniform shapes. They are useful when working with sequences of varying lengths, such as sentences of different lengths in NLP tasks.
* Example:

In [27]:
# Creating a ragged tensor
ragged_tensor = tf.ragged.constant([[1, 2], [3, 4, 5], [6]])
print(ragged_tensor)

<tf.RaggedTensor [[1, 2], [3, 4, 5], [6]]>



In TensorFlow, both constants and variables are used to hold data, but they have different properties and purposes:

1. **TensorFlow Constant:**
* Constants are immutable tensors, meaning their values cannot be changed once they are defined.
* They are typically used to represent fixed values such as hyperparameters or input data that remain constant throughout the execution of a TensorFlow graph.
* Constants are created using the tf.constant() function.

In [29]:
import tensorflow as tf

# Creating a TensorFlow constant
constant_tensor = tf.constant([1, 2, 3])
print(constant_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


2. **TensorFlow Variable:**
* Variables are mutable tensors, meaning their values can be modified during the execution of a TensorFlow graph.
* They are commonly used to hold model parameters such as weights and biases that need to be updated during training.
* Variables are created using the tf.Variable() class.

In [32]:
import tensorflow as tf

# Creating a TensorFlow variable
initial_value = tf.random.normal(shape=(3, 3))  # Example initialization
variable = tf.Variable(initial_value)
print(variable)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[-0.37941828, -0.78046685, -0.577344  ],
       [ 0.7941104 , -0.8520367 , -0.9471683 ],
       [-1.8896961 ,  1.6038125 ,  0.6834448 ]], dtype=float32)>



In TensorFlow, matrix operations like addition, multiplication, and element-wise operations are fundamental for building and training neural networks and other machine learning models. Let's break down each operation:

1. **Matrix Addition:**
Matrix addition in TensorFlow is straightforward. Given two matrices A and B, you can add them using the tf.add() function or the + operator. Here's how you would do it:

In [37]:
import tensorflow as tf
A = tf.constant([[1,2],[3,4]])
B = tf.constant([[5,6],[7,8]])

#perform matrix addition
C = tf.add(A,B)

print(C.numpy())

[[ 6  8]
 [10 12]]


2. **Matrix Multiplication:**
TensorFlow provides several ways to perform matrix multiplication. The most common methods are using the tf.matmul() function or the @ operator. Here's how you would do it:

In [38]:
import tensorflow as tf

# Define two matrices
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])

# Perform matrix multiplication
C = tf.matmul(A, B)  # Or simply C = A @ B

print(C.numpy())

[[19 22]
 [43 50]]


3. **Element-wise Operations:**
Element-wise operations are applied individually to each element of a tensor. TensorFlow provides various functions for element-wise operations such as addition, subtraction, multiplication, division, etc. Here's how you would perform element-wise operations

In [39]:
import tensorflow as tf

# Define a matrix
A = tf.constant([[1, 2], [3, 4]])

# Perform element-wise operations
# Example: Element-wise multiplication by scalar
scalar = tf.constant(2)
B = tf.multiply(A, scalar)  # Or simply B = A * scalar

print(B.numpy())

[[2 4]
 [6 8]]


You can perform similar operations with other arithmetic operations (tf.add(), tf.subtract(), tf.divide(), etc.) by applying them element-wise.

# Answer 2(A)

In [53]:
import tensorflow as tf

# Define the dimensions
rows = 2
cols = 2

# Create matrix A with random normal values
A = tf.random.normal(shape=(rows, cols))

# Display the values of matrix A
print("Matrix A:")
print(A.numpy())

# Define the dimensions for matrix B
rows_B = 3
cols_B = 3

# Create matrix B with truncated normal values (Gaussian distribution)
B = tf.random.truncated_normal(shape=(rows_B, cols_B))

# Display the values of matrix B
print("\nMatrix B:")
print(B.numpy())


Matrix A:
[[ 0.8867304   0.99678326]
 [-1.5115494   1.4831979 ]]

Matrix B:
[[-0.00714923 -1.1145269   0.35408854]
 [ 0.37060738  1.339324   -1.1520703 ]
 [-0.5679107   0.5374781  -0.17416374]]


In [54]:
import tensorflow as tf

# Define the dimensions
rows = 2
cols = 2

# Define the mean and standard deviation
mean = 2
stddev = 0.1  # Adjust this value as needed

# Create matrix C with normal distribution
C = tf.random.normal(shape=(rows, cols), mean=mean, stddev=stddev)

# Display the values of matrix C
print("Matrix C:")
print(C.numpy())

Matrix C:
[[2.1910832 2.1475186]
 [2.1101162 2.0034766]]


In [56]:
import tensorflow as tf

# Define matrices A and B with different shapes
A = tf.constant([[1, 2], [3, 4]])  # Shape: (2, 2)
B = tf.constant([[5, 6, 7], [8, 9, 10], [11, 12, 13]])  # Shape: (3, 3)

# Pad matrix A with zeros to match the shape of matrix B
A_padded = tf.pad(A, paddings=[[0, 1], [0, 1]])  # Add one row and one column of zeros

# Perform matrix addition
D = tf.add(A_padded, B)

# Display the values of matrix D
print("Matrix D:")
print(D.numpy())

Matrix D:
[[ 6  8  7]
 [11 13 10]
 [11 12 13]]


In [68]:
import tensorflow as tf

# Define matrices C and D
C = tf.constant([[1.5, 2.5], [3.5, 4.5]])  # Assuming this is the matrix C generated previously
D = tf.constant([[6, 7, 8], [9, 10, 11]],dtype=tf.float32)  # Assuming this is the matrix D generated previously

# Perform matrix multiplication
E = tf.matmul(C, D)

# Display the values of matrix E
print("Matrix E:")
print(E.numpy())

Matrix E:
[[31.5 35.5 39.5]
 [61.5 69.5 77.5]]


# Answer 2(B)

In [79]:
import tensorflow as tf

# Define the dimensions of the matrix
rows = 2
cols = 2

# Initialize the matrix with random values using TensorFlow's random_uniform function
F = tf.random.uniform(shape=[rows, cols], minval=0, maxval=1)
print(F.numpy())

[[0.45807433 0.6696968 ]
 [0.3898722  0.7073389 ]]


In [80]:
#Calculate the Transpose of F and store into G:
G = tf.transpose(F)
print(G.numpy())

[[0.45807433 0.3898722 ]
 [0.6696968  0.7073389 ]]


In [81]:
import tensorflow as tf

# Calculate the element-wise exponential of matrix F
H = tf.exp(F)
print(H.numpy())

[[1.5810266 1.9536449]
 [1.4767921 2.028586 ]]


In [82]:
# Concatenate matrices F and G horizontally
I = tf.concat([F, G], axis=1)
print(I.numpy())

[[0.45807433 0.6696968  0.45807433 0.3898722 ]
 [0.3898722  0.7073389  0.6696968  0.7073389 ]]


In [83]:
# Concatenate matrices F and G vartically
J = tf.concat([F, G], axis=0)
print(J.numpy())

[[0.45807433 0.6696968 ]
 [0.3898722  0.7073389 ]
 [0.45807433 0.3898722 ]
 [0.6696968  0.7073389 ]]
